// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "./interfaces/IDeWorkLeaseEscrow.sol";

/**
 * The standard EIP-4907 is an extension of EIP-721. It proposes an additional role (user) which can
 * be granted to addresses, and a time where the role is automatically revoked (expires). The user role
 * represents permission to "use" the NFT, but not the ability to transfer it or set users.
 */
contract DeWorkLeaseEscrow is ERC721, IDeWorkLeaseEscrow, AccessControl, ReentrancyGuard {
    struct UserInfo {
        address user; // address of user role
        uint64 expires; // unix timestamp, user expires
    }

    struct LeaseInfo {
        uint256 depositAmount;
        uint256 depositBalance;
        uint256 interestGenerated;
        string metadataURI;
        bool isActive;
    }

    using Counters for Counters.Counter;
    Counters.Counter private _tokenIdCounter;
    
    mapping(uint256 => UserInfo) private _users;
    mapping(uint256 => LeaseInfo) private _leases;
    
    string private _baseTokenURI;

    // Roles
    bytes32 public constant ARBITRATOR_ROLE = keccak256("ARBITRATOR_ROLE");

    constructor(
        string memory name_,
        string memory symbol_
    ) ERC721(name_, symbol_) {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
    }

    /// @notice Creates a new lease agreement NFT
    function createLease(
        address landlord,
        uint256 depositAmount,
        string calldata metadataURI
    ) external override onlyRole(DEFAULT_ADMIN_ROLE) returns (uint256) {
        require(depositAmount > 0, "Deposit amount must be greater than 0");
        
        _tokenIdCounter.increment();
        uint256 tokenId = _tokenIdCounter.current();
        
        _safeMint(landlord, tokenId);
        
        _leases[tokenId] = LeaseInfo({
            depositAmount: depositAmount,
            depositBalance: 0,
            interestGenerated: 0,
            metadataURI: metadataURI,
            isActive: true
        });
        
        emit LeaseCreated(tokenId, landlord, depositAmount);
        
        return tokenId;
    }

    /// @notice Allows the tenant to deposit funds for a lease
    function depositFunds(uint256 tokenId) external payable override nonReentrant {
        require(_exists(tokenId), "Lease does not exist");
        require(_leases[tokenId].isActive, "Lease is not active");
        require(msg.value > 0, "Deposit amount must be greater than 0");
        
        LeaseInfo storage lease = _leases[tokenId];
        require(lease.depositBalance + msg.value <= lease.depositAmount, "Deposit exceeds required amount");
        
        lease.depositBalance += msg.value;
        
        emit DepositUpdated(tokenId, msg.sender, msg.value, true);
    }

    /// @notice set the user and expires of a NFT
    /// @dev The zero address indicates there is no user
    /// Throws if `tokenId` is not valid NFT
    /// @param user  The new user of the NFT
    /// @param expires  UNIX timestamp, The new user could use the NFT before expires
    function setUser(
        uint256 tokenId,
        address user,
        uint64 expires
    ) public virtual override {
        require(
            _isApprovedOrOwner(msg.sender, tokenId) || hasRole(DEFAULT_ADMIN_ROLE, msg.sender),
            "ERC721: caller is not owner nor approved nor admin"
        );
        require(_exists(tokenId), "Lease does not exist");
        require(_leases[tokenId].isActive, "Lease is not active");
        
        // Optional: Check if deposit has been paid
        // require(_leases[tokenId].depositBalance >= _leases[tokenId].depositAmount, "Full deposit required before setting tenant");

        UserInfo storage info = _users[tokenId];
        info.user = user;
        info.expires = expires;

        emit UpdateUser(tokenId, user, expires);
    }

    /// @notice Claims the interest generated by deposited funds
    function claimInterest(uint256 tokenId) external override nonReentrant {
        require(_exists(tokenId), "Lease does not exist");
        require(_isApprovedOrOwner(msg.sender, tokenId), "Caller is not owner nor approved");
        
        LeaseInfo storage lease = _leases[tokenId];
        require(lease.interestGenerated > 0, "No interest to claim");
        
        uint256 interestAmount = lease.interestGenerated;
        lease.interestGenerated = 0;
        
        // In a real implementation, this would interact with DeFi protocols
        // For now, we just transfer the interest amount
        (bool success, ) = payable(msg.sender).call{value: interestAmount}("");
        require(success, "Interest transfer failed");
        
        emit InterestClaimed(tokenId, msg.sender, interestAmount);
    }

    /// @notice Releases deposit funds at end of lease
    function releaseDeposit(uint256 tokenId, address to, uint256 amount) external override nonReentrant {
        require(_exists(tokenId), "Lease does not exist");
        require(_isApprovedOrOwner(msg.sender, tokenId), "Caller is not owner nor approved");
        
        LeaseInfo storage lease = _leases[tokenId];
        require(lease.depositBalance >= amount, "Insufficient deposit balance");
        
        lease.depositBalance -= amount;
        
        // If deposit is fully released, mark lease as inactive
        if (lease.depositBalance == 0) {
            lease.isActive = false;
        }
        
        (bool success, ) = payable(to).call{value: amount}("");
        require(success, "Deposit release failed");
        
        emit DepositUpdated(tokenId, to, amount, false);
    }

    /// @notice Settle disputes by authorized arbitrator
    function settleDispute(uint256 tokenId, address to, uint256 amount) external override nonReentrant {
        require(hasRole(ARBITRATOR_ROLE, msg.sender), "Caller is not an arbitrator");
        require(_exists(tokenId), "Lease does not exist");
        
        LeaseInfo storage lease = _leases[tokenId];
        require(lease.isActive, "Lease is not active");
        require(lease.depositBalance >= amount, "Insufficient deposit balance");
        
        lease.depositBalance -= amount;
        
        // If deposit is fully released, mark lease as inactive
        if (lease.depositBalance == 0) {
            lease.isActive = false;
        }
        
        (bool success, ) = payable(to).call{value: amount}("");
        require(success, "Dispute settlement transfer failed");
        
        emit DisputeSettled(tokenId, msg.sender, to, amount);
    }

    /// @notice Get the deposit balance for a lease
    function getEscrowBalance(uint256 tokenId) external view override returns (uint256) {
        require(_exists(tokenId), "Lease does not exist");
        return _leases[tokenId].depositBalance;
    }

    /// @notice Get metadata for a lease
    function leaseMetadata(uint256 tokenId) external view override returns (string memory) {
        require(_exists(tokenId), "Lease does not exist");
        return _leases[tokenId].metadataURI;
    }

    /// @notice Get the user address of an NFT
    /// @dev The zero address indicates that there is no user or the user is expired
    /// @param tokenId The NFT to get the user address for
    /// @return The user address for this NFT
    function userOf(
        uint256 tokenId
    ) public view virtual override returns (address) {
        if (uint256(_users[tokenId].expires) >= block.timestamp) {
            return _users[tokenId].user;
        }
        return address(0);
    }

    /// @notice Get the user expires of an NFT
    /// @dev The zero value indicates that there is no user
    /// @param tokenId The NFT to get the user expires for
    /// @return The user expires for this NFT
    function userExpires(
        uint256 tokenId
    ) public view virtual override returns (uint256) {
        return _users[tokenId].expires;
    }

    /// @dev See {IERC165-supportsInterface}.
    function supportsInterface(
        bytes4 interfaceId
    ) public view virtual override(ERC721, AccessControl) returns (bool) {
        return
            interfaceId == type(IERC4907).interfaceId ||
            super.supportsInterface(interfaceId);
    }
    
    /**
     * @dev Sets the base URI for computing {tokenURI}.
     * Only callable by DEFAULT_ADMIN_ROLE.
     */
    function setBaseURI(string memory baseURI) public onlyRole(DEFAULT_ADMIN_ROLE) {
        _baseTokenURI = baseURI;
    }
    
    /**
     * @dev Base URI for computing {tokenURI}.
     * Override from ERC721 to return the custom base URI.
     */
    function _baseURI() internal view virtual override returns (string memory) {
        return _baseTokenURI;
    }

    function mint(address owner) public onlyRole(DEFAULT_ADMIN_ROLE) returns (uint256) {
        _tokenIdCounter.increment();
        uint256 tokenId = _tokenIdCounter.current();
        _safeMint(owner, tokenId);
        return tokenId;
    }

    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId,
        uint256 batchSize
    ) internal virtual override {
        super._beforeTokenTransfer(from, to, tokenId, batchSize);

        if (from != to && _users[tokenId].user != address(0)) {
            delete _users[tokenId];
            emit UpdateUser(tokenId, address(0), 0);
        }
    }

    // Simple implementation - in a real-world scenario, this would connect to DeFi protocols
    // This is a placeholder for demonstration purposes
    function updateInterestGenerated(uint256 tokenId, uint256 amount) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(_exists(tokenId), "Lease does not exist");
        _leases[tokenId].interestGenerated += amount;
    }
}
