// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
import "./IERC4907.sol";

/**
 * @title Decentralized Rental & Escrow Interface (Demonstrative)
 * @notice Combines a rental NFT with escrow functionality.  
 *         Deposits can be deployed to DeFi for yield generation  
 *         and securely returned at the end of the rental period.
 */
interface IDeWorkLeaseEscrow is IERC4907 {
    
    // ===================== Events =====================

    /**
     * @dev Emitted when a new lease (NFT) is created.
     * @param tokenId The NFT ID representing the lease
     * @param landlord The landlord’s address (NFT owner)
     * @param depositAmount The amount of deposit required for the lease
     */
    event LeaseCreated(
        uint256 indexed tokenId,
        address indexed landlord,
        uint256 depositAmount
    );

    /**
     * @dev Emitted when a deposit is updated (added or released).
     * @param tokenId The related NFT ID
     * @param from The address initiating the deposit or release
     * @param amount The deposit amount being updated
     * @param isDeposit True if it’s a deposit; false if it’s a release
     */
    event DepositUpdated(
        uint256 indexed tokenId,
        address indexed from,
        uint256 amount,
        bool isDeposit
    );

    /**
     * @dev Emitted when interest generated from the deposit is claimed.
     * @param tokenId The relevant NFT ID
     * @param claimant The address claiming the interest
     * @param amount The amount of interest claimed
     */
    event InterestClaimed(uint256 indexed tokenId, address indexed claimant, uint256 amount);

    /**
     * @dev Emitted when a dispute is settled by an authorized arbitrator.
     * @param tokenId The relevant NFT ID
     * @param arbitrator The address of the arbitrator
     * @param to The address receiving the released amount
     * @param amount The amount of deposit released
     */
    event DisputeSettled(uint256 indexed tokenId, address indexed arbitrator, address indexed to, uint256 amount);


    // ===================== Functions =====================

    /**
     * @notice Creates a new lease agreement NFT (landlord listing).
     * @param landlord The landlord’s address (NFT owner)
     * @param depositAmount The deposit required for the lease
     * @param metadataURI The URI for NFT metadata (property details, images, etc.)
     * @return tokenId The newly minted NFT ID representing this lease
     *
     * Note:
     * - The tenant will later call `depositFunds()` to pay the deposit.
     */
    function createLease(
        address landlord,
        uint256 depositAmount,
        string calldata metadataURI
    ) external returns (uint256 tokenId);

    /**
     * @notice Allows the tenant (or an authorized party) to deposit funds into the contract.
     *         This deposit is bound to the specified NFT (tokenId).
     * @param tokenId The NFT ID for which the deposit is being made
     *
     * Note:
     * - If using a native token (e.g., ETH), `msg.value` should match the required amount.
     * - If using an ERC20, you might require an external transfer or an approve + transferFrom flow.
     */
    function depositFunds(uint256 tokenId) external payable;

    /**
     * @notice Sets the tenant (ERC4907 user) for the specified NFT and defines an expiration time.
     * @param tokenId The NFT ID
     * @param user The tenant’s address
     * @param expires The Unix timestamp at which the rental period ends
     */
    function setUser(
        uint256 tokenId, 
        address user, 
        uint64 expires
    ) external;

    /**
     * @notice Allows the landlord or platform to claim interest generated by the deposited funds.
     * @param tokenId The NFT ID whose deposit generated the interest
     *
     * Note:
     * - In the implementation, define the profit-sharing logic (landlord, platform, tenant, etc.).
     */
    function claimInterest(uint256 tokenId) external;

    /**
     * @notice Called at the end of the lease or upon early termination.
     *         Releases deposit funds to the specified address (usually the tenant).
     * @param tokenId The NFT ID
     * @param to The address that will receive the released funds
     * @param amount The amount of deposit to release
     */
    function releaseDeposit(
        uint256 tokenId,
        address to,
        uint256 amount
    ) external;

    /**
     * @notice Allows an authorized arbitrator (third party) to resolve disputes by releasing
     *         a specified amount of the deposit to one party.
     * @param tokenId The NFT ID in dispute
     * @param to The address that will receive the released funds
     * @param amount The amount to be released
     *
     * Note:
     * - The contract should store and verify the arbitrator’s role or permissions.
     */
    function settleDispute(uint256 tokenId, address to, uint256 amount) external;

    /**
     * @notice Returns the current deposit balance in the contract for a given NFT.
     *         Could include unclaimed interest.
     * @param tokenId The NFT ID
     * @return balance The deposit balance (including any unclaimed interest)
     */
    function getEscrowBalance(uint256 tokenId) external view returns (uint256 balance);

    /**
     * @notice Retrieves metadata or details about a particular lease NFT, such as rental period,
     *         deposit amount, or an off-chain URI with additional info.
     * @param tokenId The NFT ID
     * @return metadataURI The metadata URI associated with this lease NFT
     */
    function leaseMetadata(uint256 tokenId) external view returns (string memory metadataURI);
}
